import { supabase, isConfigured } from './supabase-client.js';
const $=id=>document.getElementById(id);
const E=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const msg=(el,text,bad=false)=>el.innerHTML=text?`<div class="msg${bad?' error':''}">${E(text)}</div>`:'';
const slugify=s=>String(s||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,90);
const ui={setup:$('setupWarning'),login:$('loginPanel'),admin:$('adminPanel'),loginForm:$('loginForm'),loginMsg:$('loginMsg'),logout:$('logoutBtn'),form:$('articleForm'),rows:$('articleRows'),formMsg:$('formMsg'),reset:$('resetBtn'),formTitle:$('formTitle'),id:$('articleId'),titleTr:$('titleTr'),titleEn:$('titleEn'),slug:$('slug'),category:$('category'),status:$('status'),summaryTr:$('summaryTr'),summaryEn:$('summaryEn'),contentHtml:$('contentHtml'),contentEnHtml:$('contentEnHtml'),coverFile:$('coverFile'),coverUrl:$('coverUrl')};
let articles=[],currentUser=null;
function showLogin(){ui.login.classList.remove('hidden');ui.admin.classList.add('hidden');ui.logout.classList.add('hidden')}
function showAdmin(){ui.login.classList.add('hidden');ui.admin.classList.remove('hidden');ui.logout.classList.remove('hidden')}
async function refresh(){if(!isConfigured){ui.setup.classList.remove('hidden');ui.login.classList.add('hidden');return}const {data:{session}}=await supabase.auth.getSession();currentUser=session?.user||null;if(!currentUser)return showLogin();const {data,error}=await supabase.rpc('is_admin');if(error||data!==true){await supabase.auth.signOut();showLogin();return msg(ui.loginMsg,error?.message||'Bu hesap yönetici olarak yetkilendirilmemiş.',true)}showAdmin();await loadArticles()}
ui.loginForm.addEventListener('submit',async e=>{e.preventDefault();msg(ui.loginMsg,'Giriş yapılıyor…');const {error}=await supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return msg(ui.loginMsg,'Giriş başarısız: '+error.message,true);msg(ui.loginMsg,'');await refresh()});
ui.logout.addEventListener('click',async()=>{await supabase.auth.signOut();resetForm();showLogin()});
ui.titleTr.addEventListener('input',()=>{if(!ui.id.value&&!ui.slug.dataset.manual)ui.slug.value=slugify(ui.titleTr.value)});ui.slug.addEventListener('input',()=>ui.slug.dataset.manual='1');ui.reset.addEventListener('click',resetForm);
function resetForm(){ui.form.reset();ui.id.value='';ui.coverUrl.value='';delete ui.slug.dataset.manual;ui.formTitle.textContent='Yeni Makale';msg(ui.formMsg,'')}
async function upload(file){if(!file)return ui.coverUrl.value||null;if(file.size>5*1024*1024)throw new Error('Görsel 5 MB’tan büyük olamaz.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Yalnızca JPEG, PNG veya WebP yükleyebilirsin.');const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${currentUser.id}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('article-images').upload(path,file,{contentType:file.type,cacheControl:'3600'});if(error)throw error;return supabase.storage.from('article-images').getPublicUrl(path).data.publicUrl}
ui.form.addEventListener('submit',async e=>{e.preventDefault();const btn=ui.form.querySelector('button[type=submit]');btn.disabled=true;msg(ui.formMsg,'Kaydediliyor…');try{const status=ui.status.value;const payload={title_tr:ui.titleTr.value.trim(),title_en:ui.titleEn?.value.trim()||null,slug:slugify(ui.slug.value),category:ui.category.value.trim()||null,status,summary_tr:ui.summaryTr.value.trim(),summary_en:ui.summaryEn?.value.trim()||null,content_html:ui.contentHtml.value.trim(),content_en_html:ui.contentEnHtml?.value.trim()||null,cover_image_url:await upload(ui.coverFile.files[0]),published_at:status==='published'?new Date().toISOString():null};if(!payload.slug)throw new Error('Geçerli bir slug oluşturulamadı.');const q=ui.id.value?supabase.from('articles').update(payload).eq('id',ui.id.value):supabase.from('articles').insert(payload);const {error}=await q;if(error)throw error;resetForm();await loadArticles();alert('Makale başarıyla kaydedildi.')}catch(err){msg(ui.formMsg,'Kayıt başarısız: '+err.message,true)}finally{btn.disabled=false}});
async function loadArticles(){ui.rows.innerHTML='<p class="hint">Yükleniyor…</p>';const {data,error}=await supabase.from('articles').select('*').order('created_at',{ascending:false});if(error){ui.rows.innerHTML=`<div class="msg error">${E(error.message)}</div>`;return}articles=data||[];ui.rows.innerHTML=articles.length?articles.map(a=>`<div class="row"><div><strong>${E(a.title_tr)}</strong><div class="hint">/${E(a.slug)}</div></div><div>${a.status==='published'?'Yayında':'Taslak'}</div><div class="row-actions"><button class="btn" data-edit="${a.id}" type="button">Düzenle</button><button class="btn danger" data-delete="${a.id}" type="button">Sil</button></div></div>`).join(''):'<p class="hint">Henüz makale yok.</p>'}
ui.rows.addEventListener('click',async e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit){const a=articles.find(x=>x.id===edit);if(!a)return;ui.id.value=a.id;ui.titleTr.value=a.title_tr||'';if(ui.titleEn)ui.titleEn.value=a.title_en||'';ui.slug.value=a.slug||'';ui.slug.dataset.manual='1';ui.category.value=a.category||'';ui.status.value=a.status||'draft';ui.summaryTr.value=a.summary_tr||'';if(ui.summaryEn)ui.summaryEn.value=a.summary_en||'';ui.contentHtml.value=a.content_html||'';if(ui.contentEnHtml)ui.contentEnHtml.value=a.content_en_html||'';ui.coverUrl.value=a.cover_image_url||'';ui.formTitle.textContent='Makaleyi Düzenle';window.scrollTo({top:0,behavior:'smooth'})}if(del){const a=articles.find(x=>x.id===del);if(!a||!confirm(`“${a.title_tr}” silinsin mi?`))return;const {error}=await supabase.from('articles').delete().eq('id',del);if(error)return alert('Silinemedi: '+error.message);if(ui.id.value===del)resetForm();await loadArticles()}});
supabase?.auth.onAuthStateChange(()=>setTimeout(refresh,0));refresh();
